"""
app.py
------
FastAPI backend for the Car Price Prediction model.

Run from the project root:
    uvicorn app:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs

Sample curl request:
    curl -X POST "http://127.0.0.1:8000/predict" \
         -H "Content-Type: application/json" \
         -d '{
               "vehicle_age": 5,
               "km_driven": 40000,
               "mileage": 18.5,
               "engine": 1197,
               "max_power": 82.0,
               "seats": 5,
               "fuel_type": "Petrol",
               "seller_type": "Dealer",
               "transmission_type": "Manual"
             }'

Expected response:
    {"predicted_price": 485000.0}
"""

import logging
import math
import os
import time
from contextlib import asynccontextmanager
from enum import Enum
from typing import Any

import joblib
import numpy as np
import pandas as pd
import requests
from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator
from starlette.middleware.base import BaseHTTPMiddleware

try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False

# --------------------------------------------------------------------------- #
# LOGGING
# --------------------------------------------------------------------------- #
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)s]  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# CONFIG
# --------------------------------------------------------------------------- #
MODEL_PATH = "models/car_price_model.pkl"

MODEL_URL = os.environ.get(
    "MODEL_URL",
    "PASTE_YOUR_HUGGINGFACE_URL_HERE",
)

FEATURE_COLUMNS = [
    "vehicle_age",
    "km_driven",
    "mileage",
    "engine",
    "max_power",
    "seats",
    "km_per_year",
    "power_to_engine",
    "log_km_driven",
    "fuel_type_diesel",
    "fuel_type_electric",
    "fuel_type_lpg",
    "fuel_type_petrol",
    "seller_type_individual",
    "seller_type_trustmark_dealer",
    "transmission_type_manual",
]


# --------------------------------------------------------------------------- #
# VALID CATEGORICAL VALUES
# --------------------------------------------------------------------------- #
class FuelType(str, Enum):
    petrol   = "Petrol"
    diesel   = "Diesel"
    electric = "Electric"
    cng      = "CNG"
    lpg      = "LPG"


class SellerType(str, Enum):
    individual       = "Individual"
    dealer           = "Dealer"
    trustmark_dealer = "Trustmark Dealer"


class TransmissionType(str, Enum):
    manual    = "Manual"
    automatic = "Automatic"


# --------------------------------------------------------------------------- #
# INPUT SCHEMA
# --------------------------------------------------------------------------- #
class CarInput(BaseModel):
    vehicle_age:       int   = Field(..., ge=0,   le=50,        description="Age of car in years")
    km_driven:         int   = Field(..., ge=0,   le=1_000_000, description="Total kilometres driven")
    mileage:           float = Field(..., gt=0,   le=60.0,      description="Fuel efficiency in km/l")
    engine:            int   = Field(..., ge=100, le=10_000,    description="Engine displacement in CC")
    max_power:         float = Field(..., gt=0,   le=1000.0,    description="Maximum power in bhp")
    seats:             int   = Field(..., ge=2,   le=10,        description="Number of seats")
    fuel_type:         FuelType
    seller_type:       SellerType
    transmission_type: TransmissionType

    @field_validator("max_power")
    @classmethod
    def power_must_be_sensible(cls, v: float, info: Any) -> float:
        engine = (info.data or {}).get("engine")
        if engine and engine > 0 and v / engine > 0.5:
            raise ValueError(
                f"max_power ({v} bhp) / engine ({engine} CC) = {v/engine:.3f}. "
                "Ratio >0.5 bhp/CC seems unrealistic. Please check your inputs."
            )
        return v

    model_config = {
        "json_schema_extra": {
            "example": {
                "vehicle_age": 5,
                "km_driven": 40000,
                "mileage": 18.5,
                "engine": 1197,
                "max_power": 82.0,
                "seats": 5,
                "fuel_type": "Petrol",
                "seller_type": "Dealer",
                "transmission_type": "Manual",
            }
        }
    }


# --------------------------------------------------------------------------- #
# OUTPUT SCHEMA
# --------------------------------------------------------------------------- #
class PredictionOutput(BaseModel):
    predicted_price: float = Field(..., description="Estimated selling price in INR")


# --------------------------------------------------------------------------- #
# MODEL STORE
# --------------------------------------------------------------------------- #
class ModelStore:
    model           = None
    feature_columns = []
    explainer       = None
    shap_base_value = None


# --------------------------------------------------------------------------- #
# REQUEST TIMING MIDDLEWARE
# --------------------------------------------------------------------------- #
class TimingMiddleware(BaseHTTPMiddleware):
    """
    Logs how long each request took, and adds an X-Process-Time response
    header (in milliseconds). Helps spot slow predictions or SHAP
    explanation calls without needing external monitoring tools.
    """
    async def dispatch(self, request, call_next):
        start = time.perf_counter()
        response = await call_next(request)
        duration_ms = (time.perf_counter() - start) * 1000
        response.headers["X-Process-Time"] = f"{duration_ms:.2f}ms"
        log.info(f"{request.method} {request.url.path} completed in {duration_ms:.2f}ms")
        return response


# --------------------------------------------------------------------------- #
# RATE LIMITING MIDDLEWARE
# --------------------------------------------------------------------------- #
class RateLimitMiddleware(BaseHTTPMiddleware):
    """
    Simple in-memory sliding-window rate limiter, keyed by client IP.
    Caps each IP to `max_requests` per `window_seconds`.

    In-memory storage is fine here because Render is configured with
    WEB_CONCURRENCY=1 (single worker) — if this app ever scales to
    multiple workers/instances, this would need a shared store like
    Redis instead, since each worker would otherwise track its own
    separate counts.

    Health check endpoints are exempted so uptime monitors (or Render's
    own health checks) never get throttled.
    """
    EXEMPT_PATHS = {"/", "/health"}

    def __init__(self, app, max_requests: int = 30, window_seconds: int = 60):
        super().__init__(app)
        self.max_requests = max_requests
        self.window_seconds = window_seconds
        self.requests: dict[str, list[float]] = {}

    async def dispatch(self, request, call_next):
        if request.url.path in self.EXEMPT_PATHS:
            return await call_next(request)

        client_ip = request.client.host if request.client else "unknown"
        now = time.time()

        timestamps = self.requests.get(client_ip, [])
        # Drop timestamps outside the current window before counting.
        timestamps = [t for t in timestamps if now - t < self.window_seconds]

        if len(timestamps) >= self.max_requests:
            log.warning(f"Rate limit exceeded for {client_ip} on {request.url.path}")
            return JSONResponse(
                status_code=429,
                content={
                    "detail": (
                        f"Rate limit exceeded: max {self.max_requests} requests "
                        f"per {self.window_seconds} seconds. Please slow down."
                    )
                },
            )

        timestamps.append(now)
        self.requests[client_ip] = timestamps

        return await call_next(request)


# --------------------------------------------------------------------------- #
# MODEL DOWNLOAD
# --------------------------------------------------------------------------- #
def download_model():
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)

    if os.path.exists(MODEL_PATH):
        log.info(f"Model already present at '{MODEL_PATH}', skipping download.")
        return

    if not MODEL_URL or MODEL_URL == "PASTE_YOUR_HUGGINGFACE_URL_HERE":
        log.error("MODEL_URL is not set. Set it as an environment variable on Render.")
        raise RuntimeError(
            "MODEL_URL environment variable is missing or unset — "
            "cannot download model file."
        )

    log.info(f"Downloading model from {MODEL_URL} ...")
    try:
        response = requests.get(MODEL_URL, stream=True, timeout=120)
        response.raise_for_status()

        tmp_path = MODEL_PATH + ".part"
        with open(tmp_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        os.rename(tmp_path, MODEL_PATH)

        size_mb = os.path.getsize(MODEL_PATH) / 1e6
        log.info(f"Model downloaded ✅ ({size_mb:.1f} MB) -> '{MODEL_PATH}'")

    except requests.exceptions.RequestException as e:
        log.error(f"Model download failed: {e}")
        raise RuntimeError(f"Failed to download model from {MODEL_URL}: {e}")


# --------------------------------------------------------------------------- #
# APP LIFECYCLE
# --------------------------------------------------------------------------- #
@asynccontextmanager
async def lifespan(app: FastAPI):
    # --- Startup ---
    download_model()

    if not os.path.exists(MODEL_PATH):
        log.error(f"Model file not found: '{MODEL_PATH}'")
        log.error("Run 'python src/train_model.py' first.")
        raise RuntimeError(f"Model file not found: {MODEL_PATH}")

    ModelStore.model           = joblib.load(MODEL_PATH)
    ModelStore.feature_columns = list(ModelStore.model.feature_names_in_)

    log.info(f"Model loaded      : '{MODEL_PATH}'")
    log.info(f"Model type        : {type(ModelStore.model).__name__}")
    log.info(f"Features expected : {len(ModelStore.feature_columns)}")

    model_cols  = set(ModelStore.feature_columns)
    static_cols = set(FEATURE_COLUMNS)
    missing_from_static = model_cols  - static_cols
    extra_in_static     = static_cols - model_cols

    if missing_from_static:
        log.error("FEATURE_COLUMNS is missing columns the model expects:")
        for col in sorted(missing_from_static):
            log.error(f"    MISSING: {col}")
        log.error("Add the missing columns to FEATURE_COLUMNS in app.py.")
        raise RuntimeError(
            f"FEATURE_COLUMNS mismatch: missing {sorted(missing_from_static)}"
        )

    if extra_in_static:
        log.warning("FEATURE_COLUMNS contains columns the model does NOT expect:")
        for col in sorted(extra_in_static):
            log.warning(f"    EXTRA: {col}")

    log.info("FEATURE_COLUMNS validated against model — no missing columns.")
    log.info(f"Active columns: {ModelStore.feature_columns}")

    if SHAP_AVAILABLE:
        try:
            ModelStore.explainer = shap.TreeExplainer(ModelStore.model)
            ev = ModelStore.explainer.expected_value
            ModelStore.shap_base_value = float(ev[0] if hasattr(ev, "__len__") else ev)

            log.info(f"SHAP TreeExplainer initialized. "
                     f"Base value (expected prediction): {ModelStore.shap_base_value:,.0f}")
        except Exception as e:
            log.warning(f"SHAP TreeExplainer could not be initialized: {e}")
            log.warning("/predict-with-explanation will return 503 for this model type.")
            ModelStore.explainer = None
    else:
        log.warning("shap not installed — /predict-with-explanation unavailable.")
        log.warning("Install with: pip install shap")

    yield
    # --- Shutdown ---
    ModelStore.model           = None
    ModelStore.feature_columns = []
    ModelStore.explainer       = None
    ModelStore.shap_base_value = None
    log.info("Model and explainer unloaded.")


# --------------------------------------------------------------------------- #
# FASTAPI APP
# --------------------------------------------------------------------------- #
app = FastAPI(
    title="Car Price Prediction API",
    description=(
        "Predicts the selling price of a used car. "
        "Send raw human-readable inputs — the API handles all preprocessing."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — allows your Streamlit frontend (a different domain) to call this
# API from the browser. allow_origins=["*"] is fine for now during testing;
# once your Streamlit app has a fixed URL, replace "*" with that exact URL.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# GZip compression — shrinks response bodies over 1KB before sending them
# over the wire. Mainly benefits /predict-with-explanation, which returns
# 16 SHAP feature values per request.
app.add_middleware(GZipMiddleware, minimum_size=1000)

# Request timing — logs latency for every request and adds an
# X-Process-Time response header.
app.add_middleware(TimingMiddleware)

# Rate limiting — caps each client IP to 30 requests per 60 seconds,
# to protect the free-tier instance from being overwhelmed by a single
# aggressive caller. Health check paths are exempted.
app.add_middleware(RateLimitMiddleware, max_requests=30, window_seconds=60)


# --------------------------------------------------------------------------- #
# VALIDATION ERROR HANDLER
# --------------------------------------------------------------------------- #
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """
    Overrides FastAPI's default 422 response with a flatter, easier to
    read structure. The default format nests errors in a way that's
    annoying to parse on the frontend just to show "seats must be
    between 2 and 10" — this collapses each error down to a single
    field + message pair instead.
    """
    errors = []
    for err in exc.errors():
        # err["loc"] looks like ("body", "seats") — drop the leading
        # "body"/"query" marker and keep just the field name.
        field = ".".join(str(part) for part in err["loc"] if part != "body")
        errors.append({"field": field, "message": err["msg"]})

    log.warning(f"Validation failed on {request.url.path}: {errors}")

    return JSONResponse(
        status_code=422,
        content={"detail": "Validation failed", "errors": errors},
    )


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Catches anything not already handled by a specific try/except inside
    an endpoint (e.g. an unexpected error in middleware, or an edge case
    nobody anticipated). Without this, an uncaught exception would either
    crash the worker or leak a raw Python traceback — including file
    paths and internals — straight back to whoever called the API.

    The full traceback is still logged server-side via exc_info=True,
    so nothing is lost for debugging; the client just never sees it.
    """
    log.error(f"Unhandled exception on {request.url.path}: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "An unexpected error occurred. Please try again."},
    )


# --------------------------------------------------------------------------- #
# PREPROCESSING  (must mirror data_preprocessing.py exactly)
# --------------------------------------------------------------------------- #
def engineer_features(data: dict) -> dict:
    data["km_per_year"]     = data["km_driven"] / (data["vehicle_age"] + 1)
    data["power_to_engine"] = data["max_power"]  / data["engine"]
    data["log_km_driven"]   = math.log1p(data["km_driven"])
    return data


def encode_categoricals(data: dict) -> dict:
    fuel         = data.pop("fuel_type").lower()
    seller       = data.pop("seller_type").lower().replace(" ", "_")
    transmission = data.pop("transmission_type").lower().replace(" ", "_")

    data["fuel_type_diesel"]   = 1 if fuel == "diesel"   else 0
    data["fuel_type_electric"] = 1 if fuel == "electric" else 0
    data["fuel_type_lpg"]      = 1 if fuel == "lpg"      else 0
    data["fuel_type_petrol"]   = 1 if fuel == "petrol"   else 0

    data["seller_type_individual"]       = 1 if seller == "individual"       else 0
    data["seller_type_trustmark_dealer"] = 1 if seller == "trustmark_dealer" else 0

    data["transmission_type_manual"] = 1 if transmission == "manual" else 0

    return data


def build_input_dataframe(data: dict) -> pd.DataFrame:
    feature_columns = ModelStore.feature_columns
    row = {col: 0 for col in feature_columns}
    for col, value in data.items():
        if col in row:
            row[col] = value
    return pd.DataFrame([row]).reindex(columns=feature_columns)


def preprocess(raw: CarInput) -> pd.DataFrame:
    data = raw.model_dump()
    data = engineer_features(data)
    data = encode_categoricals(data)
    df   = build_input_dataframe(data)
    return df


# --------------------------------------------------------------------------- #
# ENDPOINTS
# --------------------------------------------------------------------------- #
@app.get("/", tags=["Health"])
def root():
    return {"status": "ok", "message": "API is running"}


@app.get("/health", tags=["Health"])
def health():
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")
    return {
        "status":   "ok",
        "model":    type(ModelStore.model).__name__,
        "features": len(ModelStore.feature_columns),
    }


@app.get("/model-info", tags=["Health"])
def model_info():
    """
    Returns metadata about the currently loaded model — useful for the
    frontend to introspect what features are expected, or to confirm
    whether SHAP explanations are available, without hardcoding this
    info separately on the client side.
    """
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    return {
        "model_type": type(ModelStore.model).__name__,
        "feature_count": len(ModelStore.feature_columns),
        "feature_columns": ModelStore.feature_columns,
        "explanation_available": ModelStore.explainer is not None,
        "categorical_options": {
            "fuel_type": [e.value for e in FuelType],
            "seller_type": [e.value for e in SellerType],
            "transmission_type": [e.value for e in TransmissionType],
        },
    }


@app.get("/feature-importance", tags=["Explanation"])
def feature_importance():
    """
    Returns the model's global feature importances — how much each
    feature matters across ALL predictions, not just one specific car.

    Different from /predict-with-explanation (SHAP), which explains a
    single prediction. This endpoint answers "what drives car prices
    in general?" rather than "why did THIS car get THIS price?".

    Only available for tree-based models exposing feature_importances_
    (RandomForest, XGBoost, etc.) — returns 501 otherwise.
    """
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    if not hasattr(ModelStore.model, "feature_importances_"):
        raise HTTPException(
            status_code=501,
            detail=(
                f"{type(ModelStore.model).__name__} does not expose "
                "feature_importances_. This endpoint requires a "
                "tree-based model (RandomForest, XGBoost, etc.)."
            ),
        )

    importances = ModelStore.model.feature_importances_
    feature_names = ModelStore.feature_columns

    importance_dict = {
        feature_names[i]: round(float(importances[i]), 4)
        for i in range(len(feature_names))
    }

    # Sort descending — most important feature first, easiest for a
    # frontend bar chart to consume directly without re-sorting.
    sorted_importance = dict(
        sorted(importance_dict.items(), key=lambda item: item[1], reverse=True)
    )

    return {
        "model_type": type(ModelStore.model).__name__,
        "feature_importance": sorted_importance,
    }


@app.post("/predict", response_model=PredictionOutput, tags=["Prediction"])
def predict(car: CarInput):
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        input_df = preprocess(car)
        log.info(f"Predicting | shape={input_df.shape} | "
                 f"km={car.km_driven} | age={car.vehicle_age} | "
                 f"fuel={car.fuel_type.value}")

        prediction = ModelStore.model.predict(input_df)
        price      = float(round(prediction[0], 2))

        log.info(f"Predicted price: INR {price:,.0f}")
        return PredictionOutput(predicted_price=price)

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Prediction failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")


# --------------------------------------------------------------------------- #
# BATCH PREDICTION SCHEMA + ENDPOINT
# --------------------------------------------------------------------------- #
class BatchCarInput(BaseModel):
    cars: list[CarInput] = Field(..., min_length=1, max_length=50, description="List of cars to price")


class BatchPredictionOutput(BaseModel):
    predictions: list[PredictionOutput]


@app.post("/predict-batch", response_model=BatchPredictionOutput, tags=["Prediction"])
def predict_batch(batch: BatchCarInput):
    """
    Predict selling prices for multiple cars in a single request.
    Capped at 50 cars per request to keep response times reasonable
    and avoid excessive memory use on Render's free tier.
    """
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        results = []
        for car in batch.cars:
            input_df = preprocess(car)
            prediction = ModelStore.model.predict(input_df)
            price = float(round(prediction[0], 2))
            results.append(PredictionOutput(predicted_price=price))

        log.info(f"Batch prediction | {len(results)} cars processed")
        return BatchPredictionOutput(predictions=results)

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Batch prediction failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Batch prediction failed: {str(e)}")


# --------------------------------------------------------------------------- #
# CONFIDENCE SCHEMA + ENDPOINT
# --------------------------------------------------------------------------- #
class ConfidenceOutput(BaseModel):
    predicted_price: float = Field(..., description="Estimated selling price in INR (mean across trees)")
    lower_bound:     float = Field(..., description="Lower bound of the 90% confidence interval")
    upper_bound:     float = Field(..., description="Upper bound of the 90% confidence interval")
    std_dev:         float = Field(..., description="Standard deviation across individual tree predictions")


@app.post("/predict-with-confidence", response_model=ConfidenceOutput, tags=["Prediction"])
def predict_with_confidence(car: CarInput):
    """
    Predict the selling price along with a confidence interval, using
    the spread of predictions across the individual trees in the
    RandomForest (rather than just their average).

    A tight interval means the trees mostly agree — a confident
    prediction. A wide interval means the trees disagree a lot — the
    model is essentially guessing for that input, which is useful to
    surface rather than hide behind a single number.

    Only available for ensemble models exposing estimators_
    (RandomForest, ExtraTrees, etc.) — returns 501 otherwise.
    """
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    if not hasattr(ModelStore.model, "estimators_"):
        raise HTTPException(
            status_code=501,
            detail=(
                f"{type(ModelStore.model).__name__} does not expose "
                "estimators_. This endpoint requires an ensemble model "
                "(RandomForest, ExtraTrees, etc.)."
            ),
        )

    try:
        input_df = preprocess(car)

        # Collect one prediction per tree in the forest instead of just
        # the ensemble's averaged output.
        tree_predictions = np.array([
            tree.predict(input_df)[0] for tree in ModelStore.model.estimators_
        ])

        mean_price = float(round(tree_predictions.mean(), 2))
        std_dev    = float(round(tree_predictions.std(), 2))

        # 90% interval via the 5th/95th percentile across tree predictions —
        # robust to outlier trees, doesn't assume a normal distribution.
        lower_bound = float(round(np.percentile(tree_predictions, 5), 2))
        upper_bound = float(round(np.percentile(tree_predictions, 95), 2))

        log.info(
            f"Confidence | price=₹{mean_price:,.0f} | "
            f"range=[₹{lower_bound:,.0f}, ₹{upper_bound:,.0f}] | "
            f"std=₹{std_dev:,.0f}"
        )

        return ConfidenceOutput(
            predicted_price = mean_price,
            lower_bound     = lower_bound,
            upper_bound     = upper_bound,
            std_dev         = std_dev,
        )

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Confidence prediction failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Confidence prediction failed: {str(e)}")


# --------------------------------------------------------------------------- #
# EXPLANATION SCHEMA + ENDPOINT
# --------------------------------------------------------------------------- #
class ExplanationOutput(BaseModel):
    predicted_price: float = Field(..., description="Estimated selling price in INR")
    base_value:      float = Field(..., description="Model's average prediction (SHAP baseline)")
    shap_values:     dict  = Field(..., description="Feature name -> SHAP contribution (float)")


@app.post("/predict-with-explanation", response_model=ExplanationOutput, tags=["Explanation"])
def predict_with_explanation(car: CarInput):
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    if ModelStore.explainer is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "SHAP explainer is not available. "
                "Either shap is not installed (pip install shap) or "
                "the loaded model type is not supported by TreeExplainer."
            ),
        )

    try:
        input_df = preprocess(car)

        price = float(round(ModelStore.model.predict(input_df)[0], 2))

        raw_shap = ModelStore.explainer.shap_values(input_df)
        sv_array = np.array(raw_shap).flatten()

        feature_names = ModelStore.feature_columns
        shap_dict = {
            feature_names[i]: round(float(sv_array[i]), 4)
            for i in range(len(feature_names))
        }

        log.info(
            f"Explanation | price=₹{price:,.0f} | "
            f"base=₹{ModelStore.shap_base_value:,.0f} | "
            f"top feature: {max(shap_dict, key=lambda k: abs(shap_dict[k]))}"
        )

        return ExplanationOutput(
            predicted_price = price,
            base_value      = ModelStore.shap_base_value,
            shap_values     = shap_dict,
        )

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Explanation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Explanation failed: {str(e)}")


# --------------------------------------------------------------------------- #
# ENTRYPOINT (for Render / production)
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("app:app", host="0.0.0.0", port=port)