"""
app.py
------
FastAPI backend for the Car Price Prediction model.

Run from the project root:
    uvicorn app:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs

Sample curl request:
    curl -X POST "http://127.0.0.1:8000/predict" \
         -H "Content-Type: application/json" \
         -d '{
               "vehicle_age": 5,
               "km_driven": 40000,
               "mileage": 18.5,
               "engine": 1197,
               "max_power": 82.0,
               "seats": 5,
               "fuel_type": "Petrol",
               "seller_type": "Dealer",
               "transmission_type": "Manual"
             }'

Expected response:
    {"predicted_price": 485000.0}
"""

import logging
import math
import os
from contextlib import asynccontextmanager
from enum import Enum
from typing import Any

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, field_validator

# --------------------------------------------------------------------------- #
# LOGGING
# --------------------------------------------------------------------------- #
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)s]  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# CONFIG
# --------------------------------------------------------------------------- #
MODEL_PATH = "models/car_price_model.pkl"

# FEATURE_COLUMNS defines every column the model expects, in the exact order
# it was trained on.  This is the single source of truth for build_input_dataframe().
#
# HOW THIS LIST WAS GENERATED (run after any retraining):
#   python3 -c "import joblib; m=joblib.load('models/car_price_model.pkl'); print(list(m.feature_names_in_))"
#
# WHY fuel_type_lpg IS HERE:
#   pd.get_dummies(drop_first=True) on the training dataset produced four
#   fuel_type dummies because the dataset contained five fuel categories
#   (CNG, Diesel, Electric, LPG, Petrol). CNG is dropped as the baseline.
#   fuel_type_lpg MUST be present even when the user selects a non-LPG fuel
#   — in that case its value is 0, but the column must exist in the DataFrame
#   or the model raises "Feature names seen at fit time, yet now missing".
FEATURE_COLUMNS = [
    "vehicle_age",
    "km_driven",
    "mileage",
    "engine",
    "max_power",
    "seats",
    "km_per_year",
    "power_to_engine",
    "log_km_driven",
    "fuel_type_diesel",
    "fuel_type_electric",
    "fuel_type_lpg",          # ← required; = 0 for all non-LPG fuels
    "fuel_type_petrol",
    "seller_type_individual",
    "seller_type_trustmark_dealer",
    "transmission_type_manual",
]


# --------------------------------------------------------------------------- #
# VALID CATEGORICAL VALUES
# --------------------------------------------------------------------------- #
class FuelType(str, Enum):
    petrol   = "Petrol"
    diesel   = "Diesel"
    electric = "Electric"
    cng      = "CNG"
    lpg      = "LPG"


class SellerType(str, Enum):
    individual       = "Individual"
    dealer           = "Dealer"
    trustmark_dealer = "Trustmark Dealer"


class TransmissionType(str, Enum):
    manual    = "Manual"
    automatic = "Automatic"


# --------------------------------------------------------------------------- #
# INPUT SCHEMA
# --------------------------------------------------------------------------- #
class CarInput(BaseModel):
    """
    Raw user-facing input. Pydantic validates every field before any
    preprocessing runs. Categoricals are human-readable strings; one-hot
    encoding happens server-side in preprocess().
    """
    vehicle_age:       int   = Field(..., ge=0,   le=50,        description="Age of car in years")
    km_driven:         int   = Field(..., ge=0,   le=1_000_000, description="Total kilometres driven")
    mileage:           float = Field(..., gt=0,   le=60.0,      description="Fuel efficiency in km/l")
    engine:            int   = Field(..., ge=100, le=10_000,    description="Engine displacement in CC")
    max_power:         float = Field(..., gt=0,   le=1000.0,    description="Maximum power in bhp")
    seats:             int   = Field(..., ge=2,   le=10,        description="Number of seats")
    fuel_type:         FuelType
    seller_type:       SellerType
    transmission_type: TransmissionType

    @field_validator("max_power")
    @classmethod
    def power_must_be_sensible(cls, v: float, info: Any) -> float:
        """
        Catch impossible power-to-engine ratios early.
        No production car exceeds ~0.25 bhp/CC naturally aspirated;
        we allow up to 0.5 to cover high-performance / modified cars.
        """
        engine = (info.data or {}).get("engine")
        if engine and engine > 0 and v / engine > 0.5:
            raise ValueError(
                f"max_power ({v} bhp) / engine ({engine} CC) = {v/engine:.3f}. "
                "Ratio >0.5 bhp/CC seems unrealistic. Please check your inputs."
            )
        return v

    model_config = {
        "json_schema_extra": {
            "example": {
                "vehicle_age": 5,
                "km_driven": 40000,
                "mileage": 18.5,
                "engine": 1197,
                "max_power": 82.0,
                "seats": 5,
                "fuel_type": "Petrol",
                "seller_type": "Dealer",
                "transmission_type": "Manual",
            }
        }
    }


# --------------------------------------------------------------------------- #
# OUTPUT SCHEMA
# --------------------------------------------------------------------------- #
class PredictionOutput(BaseModel):
    predicted_price: float = Field(..., description="Estimated selling price in INR")


# --------------------------------------------------------------------------- #
# MODEL STORE
# --------------------------------------------------------------------------- #
class ModelStore:
    """Holds the loaded model and its expected feature columns (loaded once at startup)."""
    model           = None
    feature_columns = []   # populated from model.feature_names_in_ at startup


# --------------------------------------------------------------------------- #
# APP LIFECYCLE
# --------------------------------------------------------------------------- #
@asynccontextmanager
async def lifespan(app: FastAPI):
    # --- Startup ---
    if not os.path.exists(MODEL_PATH):
        log.error(f"Model file not found: '{MODEL_PATH}'")
        log.error("Run 'python src/train_model.py' first.")
        raise RuntimeError(f"Model file not found: {MODEL_PATH}")

    ModelStore.model           = joblib.load(MODEL_PATH)
    ModelStore.feature_columns = list(ModelStore.model.feature_names_in_)

    log.info(f"Model loaded      : '{MODEL_PATH}'")
    log.info(f"Model type        : {type(ModelStore.model).__name__}")
    log.info(f"Features expected : {len(ModelStore.feature_columns)}")

    # Validate that the hardcoded FEATURE_COLUMNS constant matches the model.
    # A mismatch means the model was retrained and FEATURE_COLUMNS was not updated.
    model_cols  = set(ModelStore.feature_columns)
    static_cols = set(FEATURE_COLUMNS)
    missing_from_static = model_cols  - static_cols   # in model, not in our list
    extra_in_static     = static_cols - model_cols    # in our list, not in model

    if missing_from_static:
        log.error("FEATURE_COLUMNS is missing columns the model expects:")
        for col in sorted(missing_from_static):
            log.error(f"    MISSING: {col}")
        log.error("Add the missing columns to FEATURE_COLUMNS in app.py.")
        raise RuntimeError(
            f"FEATURE_COLUMNS mismatch: missing {sorted(missing_from_static)}"
        )

    if extra_in_static:
        log.warning("FEATURE_COLUMNS contains columns the model does NOT expect:")
        for col in sorted(extra_in_static):
            log.warning(f"    EXTRA: {col}")

    log.info("FEATURE_COLUMNS validated against model — no missing columns.")
    log.info(f"Active columns: {ModelStore.feature_columns}")
    yield
    # --- Shutdown ---
    ModelStore.model           = None
    ModelStore.feature_columns = []
    log.info("Model unloaded.")


# --------------------------------------------------------------------------- #
# FASTAPI APP
# --------------------------------------------------------------------------- #
app = FastAPI(
    title="Car Price Prediction API",
    description=(
        "Predicts the selling price of a used car. "
        "Send raw human-readable inputs — the API handles all preprocessing."
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# --------------------------------------------------------------------------- #
# PREPROCESSING  (must mirror data_preprocessing.py exactly)
# --------------------------------------------------------------------------- #
def engineer_features(data: dict) -> dict:
    """
    Compute the three derived features added during training.
    Formulas MUST match data_preprocessing.py add_features() exactly.

        km_per_year     = km_driven / (vehicle_age + 1)
        power_to_engine = max_power / engine
        log_km_driven   = log(1 + km_driven)   [log1p, safe at km=0]
    """
    data["km_per_year"]     = data["km_driven"] / (data["vehicle_age"] + 1)
    data["power_to_engine"] = data["max_power"]  / data["engine"]
    data["log_km_driven"]   = math.log1p(data["km_driven"])
    return data


def encode_categoricals(data: dict) -> dict:
    """
    One-hot encode the three string categoricals.
    Mirrors pd.get_dummies(drop_first=True) from data_preprocessing.py.

    Baselines (dropped category -> all dummies = 0):
        fuel_type         : CNG          (alphabetically first)
        seller_type       : Dealer       (alphabetically first)
        transmission_type : Automatic    (alphabetically first)

    When user sends the baseline value (e.g. fuel_type="CNG"), all
    fuel_type_* columns correctly stay 0.
    """
    fuel         = data.pop("fuel_type").lower()
    seller       = data.pop("seller_type").lower().replace(" ", "_")
    transmission = data.pop("transmission_type").lower().replace(" ", "_")

    # fuel_type dummies  (baseline = CNG)
    data["fuel_type_diesel"]   = 1 if fuel == "diesel"   else 0
    data["fuel_type_electric"] = 1 if fuel == "electric" else 0
    data["fuel_type_lpg"]      = 1 if fuel == "lpg"      else 0
    data["fuel_type_petrol"]   = 1 if fuel == "petrol"   else 0

    # seller_type dummies  (baseline = Dealer)
    data["seller_type_individual"]       = 1 if seller == "individual"       else 0
    data["seller_type_trustmark_dealer"] = 1 if seller == "trustmark_dealer" else 0

    # transmission_type dummies  (baseline = Automatic)
    data["transmission_type_manual"] = 1 if transmission == "manual" else 0

    return data


def build_input_dataframe(data: dict) -> pd.DataFrame:
    """
    Assemble the final single-row DataFrame in the exact column order
    the model was trained on.

    Steps:
        1. Start with all FEATURE_COLUMNS initialised to 0.
        2. Overwrite with preprocessed values.
        3. Reindex to FEATURE_COLUMNS to enforce exact order.

    Reindex is the critical safety net: even if preprocessing produces
    extra or differently-named keys, the model always sees exactly the
    columns it was trained on, in the right order.
    """
    feature_columns = ModelStore.feature_columns
    row = {col: 0 for col in feature_columns}
    for col, value in data.items():
        if col in row:
            row[col] = value
    return pd.DataFrame([row]).reindex(columns=feature_columns)


def preprocess(raw: CarInput) -> pd.DataFrame:
    """
    Full preprocessing pipeline for a single API request:
        Pydantic model
            -> plain dict
            -> add engineered features
            -> one-hot encode categoricals
            -> build aligned DataFrame
    """
    data = raw.model_dump()
    data = engineer_features(data)
    data = encode_categoricals(data)
    df   = build_input_dataframe(data)
    return df


# --------------------------------------------------------------------------- #
# ENDPOINTS
# --------------------------------------------------------------------------- #
@app.get("/", tags=["Health"])
def root():
    """Health check — confirms the API is running."""
    return {"status": "ok", "message": "Car Price Prediction API is running."}


@app.get("/health", tags=["Health"])
def health():
    """Detailed health check — confirms the model is loaded and ready."""
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")
    return {
        "status":   "ok",
        "model":    type(ModelStore.model).__name__,
        "features": len(ModelStore.feature_columns),
    }


@app.post("/predict", response_model=PredictionOutput, tags=["Prediction"])
def predict(car: CarInput):
    """
    Predict the selling price of a used car.

    - Accepts raw human-readable inputs.
    - Handles all feature engineering and one-hot encoding server-side.
    - Returns predicted price in INR.
    """
    if ModelStore.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        input_df = preprocess(car)
        log.info(f"Predicting | shape={input_df.shape} | "
                 f"km={car.km_driven} | age={car.vehicle_age} | "
                 f"fuel={car.fuel_type.value}")

        prediction = ModelStore.model.predict(input_df)
        price      = float(round(prediction[0], 2))

        log.info(f"Predicted price: INR {price:,.0f}")
        return PredictionOutput(predicted_price=price)

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"Prediction failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")